[package]
name = "emailnewsletter"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.11.0", features = ["macros"] }
tokio = { version = "1", features = ["full"] }

[lib]
path = "src/lib.rs"
[[bin]]
path = "src/main.rs"
name = "emailnewsletter"